- name: install Orchard
  community.general.homebrew:
    name: cirruslabs/cli/orchard
    state: upgraded

- name: install Tart
  community.general.homebrew:
    name: cirruslabs/cli/tart
    state: upgraded

- name: install Softnet
   community.general.homebrew:
    name: cirruslabs/cli/softnet
    state: upgraded

- name: ensure Softnet binary has a SUID-bit set
  ansible.builtin.file:
    path: /opt/homebrew/bin/softnet
    owner: root
    mode: 04755
  become: yes

- name: create Orchard Worker launchd unit
   ansible.builtin.emplate:
    src: org.cirruslabs.orchard.worker.plist.j2
    dest: /Library/LaunchDaemons/org.cirruslabs.orchard.worker.plist
  become: yes

- name: install and enable Orchard Worker launchd unit
  ansible.builtin.command: launchctl load -w /Library/LaunchDaemons/org.cirruslabs.orchard.worker.plist
  become: yes
