- name: Command Line Tools
  hosts: workers
  roles:
    - { role: elliotweiser.osx-command-line-tools }

- name: Install Homebrew
  hosts: workers
  roles:
    - geerlingguy.mac.homebrew

- hosts: workers
  tasks:
    - name: Update and upgrade Homebrew packages
      homebrew:
        update_homebrew: true
        upgrade_all: true

- name: Install Orchard Worker Service
  ansible.builtin.include_tasks:
    file: install_orchard.yml
